### ISSUE TITLE
Typescript: filter function does not respect type guards in type inference

### ISSUE THREAD

**Issue by icehaunter** [dphilipson/transducist#6]
If there a type guard function is passed to the filter in the transducer, the resulting inferred type does not respect the type guard, unlike the native filter function. It works with explicit typing, but that is obviously cumbersome in more complex situations.

```typescript
import { map, filter, transduce, compose, toArray } from 'transducist'

const k: Array<number | undefined> = [1, 2, undefined]

const l = transduce(
  k,
  compose(
    filter((i: number | undefined): i is number => i !== undefined),
    map((i) => i * 2) // Error: i  is possibly undefined
  ),
  toArray()
)

const r = k
  .filter((i: number | undefined): i is number => i !== undefined)
  .map((i) => i * 2) // No error
```

**Comment by dphilipson** [comment]
Hi @icehaunter !

My apologies for not getting to this sooner. I've added this change in version 2.2.0, and also added similar typeguard handling to `remove`, `takeWhile`, and `find` at the same time.

Thank you very much for the suggestion!
